FROM openjdk:11 as build-stage
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew build --exclude-task test
RUN cp build/libs/*.jar /app/
EXPOSE 8080
ENV TZ=Asia/Seoul
CMD java -jar arcade-0.0.1-SNAPSHOT.jar